// <auto-generated />
using System;
using Kovacs_Adela_Licenta.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kovacs_Adela_Licenta.Migrations
{
    [DbContext(typeof(Kovacs_Adela_LicentaContext))]
    [Migration("20230415130847_NumeClient")]
    partial class NumeClient
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.Cafea", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DenumireCafea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Imagine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.Property<int?>("TipAromaID")
                        .HasColumnType("int");

                    b.Property<int?>("TipBoabeID")
                        .HasColumnType("int");

                    b.Property<int?>("TipCafeaID")
                        .HasColumnType("int");

                    b.Property<int?>("TipLapteID")
                        .HasColumnType("int");

                    b.Property<int?>("TipToppingID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("TipAromaID");

                    b.HasIndex("TipBoabeID");

                    b.HasIndex("TipCafeaID");

                    b.HasIndex("TipLapteID");

                    b.HasIndex("TipToppingID");

                    b.ToTable("Cafea");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.CafeaClient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("DenumireCafea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MarimeID")
                        .HasColumnType("int");

                    b.Property<int?>("TipAromaID")
                        .HasColumnType("int");

                    b.Property<int?>("TipBoabeID")
                        .HasColumnType("int");

                    b.Property<int?>("TipCafeaID")
                        .HasColumnType("int");

                    b.Property<int?>("TipLapteID")
                        .HasColumnType("int");

                    b.Property<int?>("TipToppingID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.HasIndex("MarimeID");

                    b.HasIndex("TipAromaID");

                    b.HasIndex("TipBoabeID");

                    b.HasIndex("TipCafeaID");

                    b.HasIndex("TipLapteID");

                    b.HasIndex("TipToppingID");

                    b.ToTable("CafeaClient");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.Client", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nume")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Prenume")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Client");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.Marime", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("MarimeMl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("ID");

                    b.ToTable("Marime");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.Poveste", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("NumeClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ClientID");

                    b.ToTable("Poveste");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.TipAroma", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DenumireAroma")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("ID");

                    b.ToTable("TipAroma");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.TipBoabe", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DenumireBoabe")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("ID");

                    b.ToTable("TipBoabe");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.TipCafea", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("ID");

                    b.ToTable("TipCafea");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.TipLapte", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DenumireLapte")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("ID");

                    b.ToTable("TipLapte");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.TipTopping", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("DenumireTopping")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.HasKey("ID");

                    b.ToTable("TipTopping");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.Cafea", b =>
                {
                    b.HasOne("Kovacs_Adela_Licenta.Models.TipAroma", "TipAroma")
                        .WithMany("Cafele")
                        .HasForeignKey("TipAromaID");

                    b.HasOne("Kovacs_Adela_Licenta.Models.TipBoabe", "TipBoabe")
                        .WithMany("Cafele")
                        .HasForeignKey("TipBoabeID");

                    b.HasOne("Kovacs_Adela_Licenta.Models.TipCafea", "TipCafea")
                        .WithMany("Cafele")
                        .HasForeignKey("TipCafeaID");

                    b.HasOne("Kovacs_Adela_Licenta.Models.TipLapte", "TipLapte")
                        .WithMany("Cafele")
                        .HasForeignKey("TipLapteID");

                    b.HasOne("Kovacs_Adela_Licenta.Models.TipTopping", "TipTopping")
                        .WithMany("Cafele")
                        .HasForeignKey("TipToppingID");

                    b.Navigation("TipAroma");

                    b.Navigation("TipBoabe");

                    b.Navigation("TipCafea");

                    b.Navigation("TipLapte");

                    b.Navigation("TipTopping");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.CafeaClient", b =>
                {
                    b.HasOne("Kovacs_Adela_Licenta.Models.Client", "Client")
                        .WithMany("CafeaClient")
                        .HasForeignKey("ClientID");

                    b.HasOne("Kovacs_Adela_Licenta.Models.Marime", "Marime")
                        .WithMany("CafeleClient")
                        .HasForeignKey("MarimeID");

                    b.HasOne("Kovacs_Adela_Licenta.Models.TipAroma", "TipAroma")
                        .WithMany()
                        .HasForeignKey("TipAromaID");

                    b.HasOne("Kovacs_Adela_Licenta.Models.TipBoabe", "TipBoabe")
                        .WithMany()
                        .HasForeignKey("TipBoabeID");

                    b.HasOne("Kovacs_Adela_Licenta.Models.TipCafea", "TipCafea")
                        .WithMany()
                        .HasForeignKey("TipCafeaID");

                    b.HasOne("Kovacs_Adela_Licenta.Models.TipLapte", "TipLapte")
                        .WithMany()
                        .HasForeignKey("TipLapteID");

                    b.HasOne("Kovacs_Adela_Licenta.Models.TipTopping", "TipTopping")
                        .WithMany()
                        .HasForeignKey("TipToppingID");

                    b.Navigation("Client");

                    b.Navigation("Marime");

                    b.Navigation("TipAroma");

                    b.Navigation("TipBoabe");

                    b.Navigation("TipCafea");

                    b.Navigation("TipLapte");

                    b.Navigation("TipTopping");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.Poveste", b =>
                {
                    b.HasOne("Kovacs_Adela_Licenta.Models.Client", "Client")
                        .WithMany("Poveste")
                        .HasForeignKey("ClientID");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.Client", b =>
                {
                    b.Navigation("CafeaClient");

                    b.Navigation("Poveste");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.Marime", b =>
                {
                    b.Navigation("CafeleClient");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.TipAroma", b =>
                {
                    b.Navigation("Cafele");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.TipBoabe", b =>
                {
                    b.Navigation("Cafele");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.TipCafea", b =>
                {
                    b.Navigation("Cafele");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.TipLapte", b =>
                {
                    b.Navigation("Cafele");
                });

            modelBuilder.Entity("Kovacs_Adela_Licenta.Models.TipTopping", b =>
                {
                    b.Navigation("Cafele");
                });
#pragma warning restore 612, 618
        }
    }
}
